const { ethers } = require("hardhat");
const fs = require("fs");
const path = require("path");

async function main() {
  const [deployer] = await ethers.getSigners();

  // ──────────────────────────────────────────────
  // Replace this with the actual faculty advisor
  // wallet address before deploying to Sepolia.
  // Must NOT be the same address as the deployer.
  // ──────────────────────────────────────────────
const signers = await ethers.getSigners();
const FACULTY_ADVISOR_ADDRESS = signers[1].address;

//   if (!FACULTY_ADVISOR_ADDRESS) {
//     throw new Error(
//       "FACULTY_ADVISOR_ADDRESS is not set. Add it to your .env file before deploying."
//     );
//   }

  console.log("Deploying ClubDAO...");
  console.log("President (deployer):", deployer.address);
  console.log("Faculty Advisor:", FACULTY_ADVISOR_ADDRESS);

  const ClubDAO = await ethers.getContractFactory("ClubDAO");

  const initialTreasury = ethers.parseEther("0.1");

  const clubDAO = await ClubDAO.deploy(FACULTY_ADVISOR_ADDRESS, {
    value: initialTreasury,
  });

  await clubDAO.waitForDeployment();

  const deployedAddress = await clubDAO.getAddress();

  console.log("ClubDAO deployed to:", deployedAddress);
  console.log("Initial treasury funded:", ethers.formatEther(initialTreasury), "ETH");

  // ──────────────────────────────────────────────
  // Write deployed address to frontend constants
  // ──────────────────────────────────────────────
  const frontendConstantsDir = path.join(
    __dirname,
    "..",
    "frontend",
    "src",
    "constants"
  );

  if (!fs.existsSync(frontendConstantsDir)) {
    fs.mkdirSync(frontendConstantsDir, { recursive: true });
  }

  const addressFileContent = `// Auto-generated by scripts/deploy.js — do not edit manually
export const CONTRACT_ADDRESS = "${deployedAddress}";
`;

  fs.writeFileSync(
    path.join(frontendConstantsDir, "contractAddress.js"),
    addressFileContent
  );

  console.log("Wrote contract address to frontend/src/constants/contractAddress.js");

  // ──────────────────────────────────────────────
  // Copy ABI from artifacts to frontend constants
  // ──────────────────────────────────────────────
  const artifactPath = path.join(
    __dirname,
    "..",
    "artifacts",
    "contracts",
    "ClubDAO.sol",
    "ClubDAO.json"
  );

  const artifact = JSON.parse(fs.readFileSync(artifactPath, "utf8"));

  const abiFileContent = `// Auto-generated by scripts/deploy.js — do not edit manually
export const CONTRACT_ABI = ${JSON.stringify(artifact.abi, null, 2)};
`;

  fs.writeFileSync(
    path.join(frontendConstantsDir, "contractABI.js"),
    abiFileContent
  );

  console.log("Wrote contract ABI to frontend/src/constants/contractABI.js");
  console.log("Deployment complete.");
}

main()
  .then(() => process.exit(0))
  .catch((error) => {
    console.error(error);
    process.exit(1);
  });